# PyTorch

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/logo.png" width=150>

In this lesson we'll learn about PyTorch which is a machine learning library used to build dynamic neural networks. We'll learn about the basics, like creating and using Tensors, in this lesson but we'll be making models with it in the next lesson.

<img src="https://raw.githubusercontent.com/GokuMohandas/practicalAI/master/images/pytorch.png" width=300>

# Tensor basics

In [1]:
# Load PyTorch library
!pip3 install torch

In [0]:
import numpy as np
import torch

In [3]:
# Creating a zero tensor
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))

Type: torch.FloatTensor
Size: torch.Size([3, 4])
Values: 
tensor([[2.0988e-36, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3733e-14, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28]])


In [5]:
# Creating a random tensor
x = torch.randn(2, 3) # normal distribution (rand(2,3) -> uniform distribution)
print (x)

tensor([[ 0.5291, -0.1647,  0.8269],
        [-0.3980, -1.1361, -1.1420]])


In [6]:
# Zero and Ones tensor
x = torch.zeros(2, 3)
print (x)
x = torch.ones(2, 3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
# List → Tensor
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [10]:
# NumPy array → Tensor
x = torch.from_numpy(np.random.rand(2, 3))
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

Size: torch.Size([2, 3])
Values: 
tensor([[0.7868, 0.9003, 0.2033],
        [0.9712, 0.6687, 0.2582]], dtype=torch.float64)


In [11]:
# Changing tensor type
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
x = x.long()
print("Type: {}".format(x.type()))

Type: torch.FloatTensor
Type: torch.LongTensor


# Tensor operations

In [12]:
# Addition
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = x + y
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([2, 3])
Values: 
tensor([[-0.5934,  3.3791,  1.9349],
        [ 1.4639, -0.0575, -4.1537]])


In [13]:
# Dot product
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([2, 2])
Values: 
tensor([[ 0.5641, -0.8687],
        [-1.6931, -0.5521]])


In [14]:
# Transpose
x = torch.randn(2, 3)
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))
y = torch.t(x)
print("Size: {}".format(y.shape)) 
print("Values: \n{}".format(y))

Size: torch.Size([2, 3])
Values: 
tensor([[-0.8238,  0.7796, -0.9485],
        [ 0.7418, -0.6073,  1.5705]])
Size: torch.Size([3, 2])
Values: 
tensor([[-0.8238,  0.7418],
        [ 0.7796, -0.6073],
        [-0.9485,  1.5705]])


In [15]:
# Reshape
z = x.view(3, 2)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[-0.8238,  0.7796],
        [-0.9485,  0.7418],
        [-0.6073,  1.5705]])


In [16]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print("Size: {}".format(x.shape)) 
print("Values: \n{}\n".format(x))
a = x.view(x.size(1), -1)
print("Size: {}".format(a.shape)) 
print("Values: \n{}\n".format(a))
b = x.transpose(0,1).contiguous()
print("Size: {}".format(b.shape)) 
print("Values: \n{}\n".format(b))
c = b.view(b.size(0), -1)
print("Size: {}".format(c.shape)) 
print("Values: \n{}".format(c))

Size: torch.Size([2, 3, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])

Size: torch.Size([3, 2, 4])
Values: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])

Size: torch.Size([3, 8])
Values: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10],
        [ 2,  2,  2,  2, 20, 20, 20, 20],
        [ 3,  3,  3,  3, 30, 30, 30, 30]])


In [17]:
# Dimensional operations
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.sum(x, dim=0) # add each row's value for every column
print("Values: \n{}".format(y))
z = torch.sum(x, dim=1) # add each columns's value for every row
print("Values: \n{}".format(z))

Values: 
tensor([[ 1.7167, -0.5780,  1.9998],
        [ 0.2968, -0.7215, -1.3749]])
Values: 
tensor([ 2.0135, -1.2994,  0.6249])
Values: 
tensor([ 3.1385, -1.7995])


# Indexing, Splicing and Joining

In [18]:
x = torch.randn(3, 4)
print("x: \n{}".format(x))
print ("x[:1]: \n{}".format(x[:1]))
print ("x[:1, 1:3]: \n{}".format(x[:1, 1:3]))

x: 
tensor([[ 1.0086, -0.2617, -1.4371,  0.1490],
        [ 0.9478, -0.8858, -0.0879,  0.5678],
        [-0.1941, -0.4500,  0.8553,  1.8984]])
x[:1]: 
tensor([[ 1.0086, -0.2617, -1.4371,  0.1490]])
x[:1, 1:3]: 
tensor([[-0.2617, -1.4371]])


In [19]:
# Select with dimensional indicies
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices) # values from column 0 & 2
print("Values: \n{}".format(chosen)) 
row_indices = torch.LongTensor([0, 1])
chosen = x[row_indices, col_indices] # values from (0, 0) & (2, 1)
print("Values: \n{}".format(chosen)) 

Values: 
tensor([[ 0.2908, -0.9719, -1.3136],
        [ 0.2686, -0.2655, -1.0784]])
Values: 
tensor([[ 0.2908, -1.3136],
        [ 0.2686, -1.0784]])
Values: 
tensor([ 0.2908, -1.0784])


In [20]:
# Concatenation
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.cat([x, x], dim=0) # stack by rows (dim=1 to stack by columns)
print("Values: \n{}".format(y))

Values: 
tensor([[-0.9394,  1.4911,  1.3202],
        [ 0.2749,  0.4506, -0.7165]])
Values: 
tensor([[-0.9394,  1.4911,  1.3202],
        [ 0.2749,  0.4506, -0.7165],
        [-0.9394,  1.4911,  1.3202],
        [ 0.2749,  0.4506, -0.7165]])


# Gradients

In [21]:
# Tensors with gradient bookkeeping
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward() # z has to be scalar
print("Values: \n{}".format(x))
print("x.grad: \n", x.grad)

Values: 
tensor([[0.6985, 0.3998, 0.1060, 0.5707],
        [0.1189, 0.3646, 0.0714, 0.2129],
        [0.0918, 0.1151, 0.6048, 0.4133]], requires_grad=True)
x.grad: 
 tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


* $ y = 3x + 2 $
* $ z = \sum{y}/N $
* $ \frac{\partial(z)}{\partial(x)} = \frac{\partial(z)}{\partial(y)} \frac{\partial(y)}{\partial(x)} = \frac{1}{N} * 3 = \frac{1}{12} * 3 = 0.25 $

# CUDA tensors

In [22]:
# Is CUDA available?
print (torch.cuda.is_available())

True


If the code above return False, then go to `Runtime` → `Change runtime type` and select `GPU` under `Hardware accelerator`. 

In [23]:
# Creating a zero tensor
x = torch.Tensor(3, 4).to("cpu")
print("Type: {}".format(x.type()))

Type: torch.FloatTensor


In [24]:
# Creating a zero tensor
x = torch.Tensor(3, 4).to("cuda")
print("Type: {}".format(x.type()))

Type: torch.cuda.FloatTensor
