## Introduction

The objective of this session is to practice with basic tensor manipulations in pytorch, to understand the
relation between a tensor and its underlying storage, and get a sense of the eciency of tensor-based
computation compared to their equivalent python iterative implementations.

In [1]:
import torch, time
from torch import Tensor

## Multiple views of a storage

Generate the matrix
![Task 1](task 1 matrix.png)

with no python loop.

**Hint**: Use several torch.narrow , and torch.fill .

In [2]:
m = Tensor(13, 13).fill_(1)

m.narrow(0, 1, 1).fill_(2)
m.narrow(1, 1, 1).fill_(2)
m.narrow(0, 6, 1).fill_(2)
m.narrow(1, 6, 1).fill_(2)
m.narrow(0, 11, 1).fill_(2)
m.narrow(1, 11, 1).fill_(2)

m.narrow(0, 3, 2).narrow(1, 3, 2).fill_(3)
m.narrow(0, 3, 2).narrow(1, 8, 2).fill_(3)
m.narrow(0, 8, 2).narrow(1, 3, 2).fill_(3)
m.narrow(0, 8, 2).narrow(1, 8, 2).fill_(3)

tensor([[3., 3.],
        [3., 3.]])

In [4]:
m

tensor([[1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.]])

#### numpy style

In [5]:
m = Tensor(13, 13).fill_(1)

m[3:5,3:5] = 3
m[8:10,3:5] = 3
m[3:5,8:10] = 3
m[8:10,8:10] = 3

m[:,1::5] = 2
m[1::5,:] = 2

In [6]:
m

tensor([[1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.]])

## Eigendecomposition

Without using python loops, create a square matrix M (a 2d tensor) of dimension 20 X 20, filled with
random Gaussian coeffcients, and compute the eigenvalues of M^-1 diag(1; : : : ; 20)M.

**Hint**: Use torch.arange , torch.diag , torch.mm , torch.inverse , torch.normal and torch.eig .

In [26]:
size = 20
m = torch.Tensor(size, size).normal_()

In [27]:
inv_m = m.inverse()
diag_tensor = torch.arange(1,size + 1).diag()

In [29]:
diag_tensor = diag_tensor.float()

In [30]:
torch.mm(inv_m, torch.mm(diag_tensor, m)).eig()

(tensor([[20.0000,  0.0000],
         [19.0000,  0.0000],
         [ 1.0000,  0.0000],
         [18.0000,  0.0000],
         [ 2.0000,  0.0000],
         [17.0000,  0.0000],
         [16.0000,  0.0000],
         [ 3.0000,  0.0000],
         [ 4.0000,  0.0000],
         [ 5.0000,  0.0000],
         [15.0000,  0.0000],
         [14.0000,  0.0000],
         [ 6.0000,  0.0000],
         [13.0000,  0.0000],
         [ 7.0000,  0.0000],
         [ 8.0000,  0.0000],
         [12.0000,  0.0000],
         [11.0000,  0.0000],
         [10.0000,  0.0000],
         [ 9.0000,  0.0000]]), tensor([]))

## Flops per second

Generate two square matrices of dimension 5000 X 5000 filled with random Gaussian coeffcients,
compute their product, measure the time it takes, and estimate how many 
oating point products
have been executed per second (should be in the billions or tens of billions).

**Hint**: Use torch.normal , torch.mm , and time.perf counter .

In [31]:
size = 5000
first_ten = secon_ten = torch.Tensor(size, size).normal_()

t1_start = time.perf_counter()
torch.mm(first_ten, secon_ten)
t1_stop = time.perf_counter()

In [33]:
print("Elapsed time: " + str((t1_stop-t1_start)/60) + " min" )

Elapsed time: 0.052806960913415045 min


Additional reading: 

https://habr.com/company/intel/blog/144388/

https://en.wikipedia.org/wiki/FLOPS

### Playing with strides

Write a function mul row , using python loops, that gets a 2d tensor as argument, and returns a
tensor of same size, equal to the one given as argument, with the first row kept unchanged, the second
multiplied by two, the third by three, etc. For instance:

![Task 2](task 2.png)

In [70]:
def mul_row(m):
    for index, row in enumerate(m,1):
        m[index-1,:] = index * m[index-1,:]
        
def mul_row_fast(m):
    m_tmp = torch.arange(1,m.size()[0]+1).view(m.size()[0],1)
    m_tmp = m_tmp.long()
    m = m.long()
    torch.mul(m_tmp,m)

In [71]:
m = (Tensor (4 , 8).fill_ (2.0), Tensor (10000 , 400).fill_ (2.0))

In [74]:
for tensor in m:
    print("For " + str(tensor.size()))
    
    t1_start = time.perf_counter()
    mul_row(tensor)
    t1_stop = time.perf_counter()
    tloop = (t1_stop-t1_start)/60

    t1_start = time.perf_counter()
    mul_row_fast(tensor)
    t1_stop = time.perf_counter()
    ttorch = (t1_stop-t1_start)/60

    print(" LOOP elapsed time: " + str(tloop) + " min" )
    print(" PYTORCH elapsed time: " + str(ttorch) + " min" )
    print(" ratio LOOPtime / PYTORCHtime: " + str(tloop/ttorch) + "\n")

For torch.Size([4, 8])
 LOOP elapsed time: 7.116169066042252e-06 min
 PYTORCH elapsed time: 1.7585148555099295e-05 min
 ratio LOOPtime / PYTORCHtime: 0.40466926075405396

For torch.Size([10000, 400])
 LOOP elapsed time: 0.0030554537738093283 min
 PYTORCH elapsed time: 0.0009453214780686873 min
 ratio LOOPtime / PYTORCHtime: 3.2321848648268183

